language: python
dist: bionic
install:
  - cd 2019/robotfw
  - pip install pipenv
  - export PIPENV_VENV_IN_PROJECT=true
  - pipenv --venv
  - pipenv install
cache:
  - virtualenv
script:
  - pipenv run robot tests/jukebox.robot
after_failure:
  - cat stdout.log
  - cat stderr.log
