language: python
dist: bionic
install:
  - cd 2019/robotfw
  - pip install pipenv
  - pipenv lock
  - pipenv install
script:
  - pipenv run robot tests/jukebox.robot
after_failure:
  - cat stdout.log
  - cat stderr.log
